import CoreVideo
import Foundation
import Testing
import simd
@testable import MapEverything

private final class PanScanFixtureBundle: NSObject {}

/// Replays a daylight pan-in-place street scan (11 Depth Anything frames over
/// 21 s, ~1.4 m of travel, 15-21 degrees of rotation between frames) whose
/// preview showed missing areas and mild distortion. What the recording
/// established:
///
/// - Frame rate: frames landed every ~2.1 s instead of the 0.5 s design
///   interval. With a point-cloud target (Save Local counts), the frame path
///   fused the full-resolution overlay mesh into the map; Debug builds made
///   it ~15x slower still. Each far region left the view after ~3.5 frames,
///   before the evidence ratchet could mature its anchors - so the
///   integration cap sat at 5-8 m and the far side of the street (10-20 m)
///   was never mapped. The frame path now integrates the designed
///   resolution; that effect is structural and cannot be replayed from an
///   11-frame recording.
/// - Calibration bend: frames pinned at offset = 0 overshoot the near field
///   and compress 4-6 m by 5-15% against their own LiDAR (LiDAR and poses
///   agree frame to frame to ~1%).
///
/// Measured and deliberately NOT shipped (keep the numbers before retrying):
/// - Guarded negative offsets halve the 4-6 m bias (-5.2% -> -2.5%) but lose
///   8-12 m completeness (89% -> 83%) and add 4-8 m disagreement.
/// - Two-sighting anchor maturation (incidence floor 0.75) doubles 12-18 m
///   completeness here (37% -> 73%) but lets family-inconsistent far anchors
///   qualify on the near-static scan6 replay: >11 m spread p90 3.98 -> 10.5 m.
///
/// The fixture's relative maps were REGENERATED by running the bundled
/// model on the recorded camera frames (correlation >= 0.998 with the device
/// output, affine ~identity), because the recorded clouds were truncated at
/// the device's integration caps; see tools/replay_fixture/README.md. The
/// published LiDAR is sparse and range-limited, so a frame can drop here
/// that the device (dense LiDAR) kept.
struct PanScanReplayTests {
    struct Frame {
        let transform: simd_float4x4
        let relative: RelativeDepthMap
        let lidar: CVPixelBuffer
        /// (x, y, depth) on the relative map's own grid.
        let lidarSamples: [SIMD3<Float>]
    }

    struct Fixture {
        let intrinsics: simd_float3x3
        let imageResolution: CGSize
        let frames: [Frame]
    }

    static func loadFixture() throws -> Fixture {
        let url = try #require(Bundle(for: PanScanFixtureBundle.self)
            .url(forResource: "PanScanReplayFrames", withExtension: "json"))
        let root = try #require(try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
        var intrinsics = matrix_identity_float3x3
        intrinsics[0][0] = (root["fx"] as! NSNumber).floatValue
        intrinsics[1][1] = (root["fy"] as! NSNumber).floatValue
        intrinsics[2][0] = (root["cx"] as! NSNumber).floatValue
        intrinsics[2][1] = (root["cy"] as! NSNumber).floatValue
        let resolution = CGSize(width: (root["imageWidth"] as! NSNumber).doubleValue,
                                height: (root["imageHeight"] as! NSNumber).doubleValue)
        var frames: [Frame] = []
        for entry in root["frames"] as! [[String: Any]] {
            let c = (entry["transform"] as! [NSNumber]).map(\.floatValue)
            let transform = simd_float4x4(columns: (
                SIMD4(c[0], c[1], c[2], c[3]), SIMD4(c[4], c[5], c[6], c[7]),
                SIMD4(c[8], c[9], c[10], c[11]), SIMD4(c[12], c[13], c[14], c[15])
            ))
            let width = (entry["relativeWidth"] as! NSNumber).intValue
            let height = (entry["relativeHeight"] as! NSNumber).intValue
            let halfData = try #require(Data(base64Encoded: entry["relativeFloat16"] as! String))
            var values = [Float](repeating: .nan, count: width * height)
            halfData.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
                let halves = raw.bindMemory(to: Float16.self)
                for index in 0..<min(halves.count, values.count) { values[index] = Float(halves[index]) }
            }
            let lidarData = try #require(Data(base64Encoded: entry["lidarSamples"] as! String))
            var samples: [SIMD3<Float>] = []
            lidarData.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
                let floats = raw.bindMemory(to: Float32.self)
                for i in stride(from: 0, to: floats.count - 2, by: 3) {
                    samples.append(SIMD3(floats[i] * Float(width) / 518, floats[i + 1] * Float(height) / 392, floats[i + 2]))
                }
            }
            frames.append(Frame(
                transform: transform,
                relative: RelativeDepthMap(width: width, height: height, data: values),
                lidar: try makeLidarBuffer(samples: lidarData),
                lidarSamples: samples
            ))
        }
        return Fixture(intrinsics: intrinsics, imageResolution: resolution, frames: frames)
    }

    private static func makeLidarBuffer(samples: Data) throws -> CVPixelBuffer {
        let width = 256, height = 192
        var result: CVPixelBuffer?
        try #require(CVPixelBufferCreate(kCFAllocatorDefault, width, height,
                                         kCVPixelFormatType_DepthFloat32, nil, &result) == kCVReturnSuccess)
        let buffer = try #require(result)
        CVPixelBufferLockBaseAddress(buffer, [])
        defer { CVPixelBufferUnlockBaseAddress(buffer, []) }
        let base = try #require(CVPixelBufferGetBaseAddress(buffer)).assumingMemoryBound(to: Float32.self)
        let rowStride = CVPixelBufferGetBytesPerRow(buffer) / MemoryLayout<Float32>.stride
        for row in 0..<height { for col in 0..<width { base[row * rowStride + col] = 0 } }
        samples.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let floats = raw.bindMemory(to: Float32.self)
            for index in stride(from: 0, to: floats.count - 2, by: 3) {
                let px = Int((floats[index] / 518 * Float(width)).rounded())
                let py = Int((floats[index + 1] / 392 * Float(height)).rounded())
                guard px >= 0, px < width, py >= 0, py < height else { continue }
                let z = floats[index + 2]
                let existing = base[py * rowStride + px]
                if existing <= 0 || z < existing { base[py * rowStride + px] = z }
            }
        }
        return buffer
    }

    struct Metrics {
        var kept = 0
        var lidarError: [[Float]] = [[], [], []]        // signed rel error by band <2, 2-4, 4-6 m
        var interFrame: [Float] = []                     // |rel| same-surface disagreement, consecutive kept frames
        var interFrameNear: [Float] = []                 // same, restricted to LiDAR range (< 5 m)
        var interFrameBands: [[Float]] = [[], [], [], []] // 0-4, 4-8, 8-12, 12-18 m
        var caps: [Float] = []
        var coverage: [Float] = []                       // per-frame fraction of in-cap geometry present in the fused TSDF
        /// Scene completeness by depth band (0-4, 4-8, 8-12, 12-18 m): the
        /// fraction of every pixel each frame saw (at its own calibration)
        /// whose surface the final fused TSDF contains. Holes AND content
        /// the integration cap never admitted both count as missing.
        var completeness: [[Int]] = Array(repeating: [0, 0], count: 4)
        var offsets: [Float] = []
        var tsdfVertices = 0

        static func median(_ values: [Float]) -> Float {
            guard !values.isEmpty else { return .nan }
            let sorted = values.sorted()
            return sorted[sorted.count / 2]
        }
        static func percentile(_ values: [Float], _ p: Double) -> Float {
            guard !values.isEmpty else { return .nan }
            let sorted = values.sorted()
            return sorted[min(sorted.count - 1, Int(Double(sorted.count) * p))]
        }
        var summary: String {
            let bands = lidarError.map { String(format: "%+.1f%%(|%.1f%%|)", Self.median($0) * 100, Self.median($0.map(abs)) * 100) }
            let bandsC = completeness.map { String(format: "%.0f%%", Float($0[0]) / Float(max(1, $0[1])) * 100) }.joined(separator: "/")
            let bandsI = interFrameBands.map { $0.count < 200 ? "-" : String(format: "%.1f%%", Self.median($0) * 100) }.joined(separator: "/")
            let capList = caps.map { String(format: "%.1f", $0) }.joined(separator: ",")
            return "completeness 0-4/4-8/8-12/12-18 m: \(bandsC) | disagreement 0-4/4-8/8-12/12-18 m: \(bandsI) | caps \(capList) | " + String(format: "kept %d | LiDAR err <2/2-4/4-6 m: %@ | inter-frame |dz|/z median %.1f%% p90 %.1f%% (in LiDAR range %.1f%%) | TSDF coverage mean %.1f%% min %.1f%% | tsdf vertices %d | offsets %@",
                          kept, bands.joined(separator: " "), Self.median(interFrame) * 100, Self.percentile(interFrame, 0.9) * 100,
                          Self.median(interFrameNear) * 100,
                          coverage.reduce(0, +) / Float(max(1, coverage.count)) * 100, (coverage.min() ?? 0) * 100,
                          tsdfVertices, offsets.map { String(format: "%.3f", $0) }.joined(separator: ","))
        }
    }

    /// The per-frame pipeline exactly as ARViewContainer runs it for the
    /// accumulated scene, plus the three reconstruction-quality metrics.
    static func replay(_ fixture: Fixture,
                       configuration: DepthCalibrationPipeline.Configuration = .default) async -> Metrics {
        let map = AccumulatedDepthMesh()
        let volume = TSDFVolume()
        var metrics = Metrics()
        var kept: [(frame: Frame, calibration: DepthAnythingProcessor.MaximumLikelihoodCalibration,
                    cap: Float, vertices: [SIMD3<Float>])] = []
        var allFrames: [(frame: Frame, calibration: DepthAnythingProcessor.MaximumLikelihoodCalibration)] = []
        for frame in fixture.frames {
            let anchors = await map.calibrationAnchors()
            guard let result = DepthCalibrationPipeline.calibrate(
                relative: frame.relative, lidarDepthMap: frame.lidar, lidarConfidenceMap: nil,
                anchors: anchors, intrinsics: fixture.intrinsics,
                imageResolution: fixture.imageResolution, transform: frame.transform,
                configuration: configuration
            ) else { continue }
            let base = MeshGenerator.DepthAnythingMeshConfiguration.accumulatedScene
            let configuration = MeshGenerator.DepthAnythingMeshConfiguration(
                step: 1, minimumDepth: base.minimumDepth,
                maximumDepth: min(base.maximumDepth, result.integrationDepthCap),
                maximumDepthDiscontinuity: base.maximumDepthDiscontinuity,
                maximumTriangleCount: base.maximumTriangleCount
            )
            guard let mesh = MeshGenerator.createDepthAnythingMeshSnapshot(
                from: frame.relative, calibration: result.calibration, intrinsics: fixture.intrinsics,
                imageResolution: fixture.imageResolution, transform: frame.transform, configuration: configuration
            ) else { continue }
            let colored = MeshGenerator.DepthAnythingMeshSnapshot(
                descriptor: mesh.descriptor, vertices: mesh.vertices, indices: mesh.indices,
                colors: Array(repeating: SIMD3<UInt8>(180, 180, 180), count: mesh.vertices.count),
                cameraPosition: mesh.cameraPosition, cameraTransform: mesh.cameraTransform,
                intrinsics: mesh.intrinsics, imageResolution: mesh.imageResolution,
                beyondCapCarriers: mesh.beyondCapCarriers
            )
            _ = await map.integrate(colored, calibrationSource: result.source)
            let metric = metricDepth(frame.relative, result.calibration, cap: result.integrationDepthCap)
            _ = await volume.integrate(
                depth: metric, colors: nil, width: frame.relative.width, height: frame.relative.height,
                intrinsics: fixture.intrinsics, imageResolution: fixture.imageResolution,
                transform: frame.transform, maximumDepth: result.integrationDepthCap,
                weightScale: result.source == .meshPropagated ? 0.25 : 1
            )
            metrics.offsets.append(result.calibration.offset)
            metrics.caps.append(result.integrationDepthCap)
            allFrames.append((frame, result.calibration))
            kept.append((frame, result.calibration, result.integrationDepthCap, mesh.vertices))

            // Calibration accuracy against this frame's own LiDAR.
            frame.relative.withReadAccess { reader in
                for sample in frame.lidarSamples {
                    let x = Int(sample.x.rounded()), y = Int(sample.y.rounded())
                    guard x >= 0, x < frame.relative.width, y >= 0, y < frame.relative.height, sample.z > 0.1,
                          let predicted = DepthAnythingProcessor.calibratedMetricDepth(
                            relativeDepth: reader.value(atX: x, y: y), calibration: result.calibration) else { continue }
                    let error = (predicted - sample.z) / sample.z
                    guard abs(error) < 0.5 else { continue }
                    let band = sample.z < 2 ? 0 : (sample.z < 4 ? 1 : (sample.z < 6 ? 2 : -1))
                    if band >= 0 { metrics.lidarError[band].append(error) }
                }
            }
        }
        metrics.kept = kept.count

        // Same-surface disagreement: project frame a's integrated geometry
        // into frame b's calibrated depth image.
        for (a, b) in zip(kept, kept.dropFirst()) {
            let depthB = metricDepth(b.frame.relative, b.calibration, cap: b.cap)
            let (fx, fy, cx, cy) = gridIntrinsics(fixture, b.frame.relative)
            let worldToB = b.frame.transform.inverse
            for vertex in a.vertices {
                let camera = worldToB * SIMD4<Float>(vertex.x, vertex.y, vertex.z, 1)
                let z = -camera.z
                guard z > 0.1 else { continue }
                let px = Int((cx + fx * camera.x / z).rounded()), py = Int((cy - fy * camera.y / z).rounded())
                guard px >= 0, px < b.frame.relative.width, py >= 0, py < b.frame.relative.height else { continue }
                let measured = depthB[py * b.frame.relative.width + px]
                guard measured.isFinite else { continue }
                let rel = abs(measured - z) / z
                guard rel < 0.5 else { continue }   // occlusion / disocclusion, not disagreement
                metrics.interFrame.append(rel)
                if z < 5 { metrics.interFrameNear.append(rel) }
                metrics.interFrameBands[z < 4 ? 0 : (z < 8 ? 1 : (z < 12 ? 2 : 3))].append(rel)
            }
        }

        // Holes: fraction of each frame's integrated geometry that the fused
        // TSDF surface actually contains (within ~2 voxels).
        let fused = await volume.extractMesh()
        metrics.tsdfVertices = fused.vertices.count
        let cell: Float = 0.12
        func key(_ p: SIMD3<Float>) -> SIMD3<Int32> { SIMD3<Int32>(Int32((p.x / cell).rounded(.down)), Int32((p.y / cell).rounded(.down)), Int32((p.z / cell).rounded(.down))) }
        let occupied = Set(fused.vertices.map(key))
        let coarseCell: Float = 0.5
        func coarseKey(_ p: SIMD3<Float>) -> SIMD3<Int32> { SIMD3<Int32>(Int32((p.x / coarseCell).rounded(.down)), Int32((p.y / coarseCell).rounded(.down)), Int32((p.z / coarseCell).rounded(.down))) }
        let coarseOccupied = Set(fused.vertices.map(coarseKey))
        func present(_ p: SIMD3<Float>, depth: Float) -> Bool {
            let fine = depth < 6
            let k = fine ? key(p) : coarseKey(p)
            for dx in Int32(-1)...1 { for dy in Int32(-1)...1 { for dz in Int32(-1)...1 {
                if (fine ? occupied : coarseOccupied).contains(k &+ SIMD3(dx, dy, dz)) { return true }
            } } }
            return false
        }
        for entry in allFrames {
            let (fx, fy, cx, cy) = gridIntrinsics(fixture, entry.frame.relative)
            let depth = metricDepth(entry.frame.relative, entry.calibration, cap: 18)
            let w = entry.frame.relative.width
            for py in Swift.stride(from: 0, to: entry.frame.relative.height, by: 2) {
                for px in Swift.stride(from: 0, to: w, by: 2) {
                    let z = depth[py * w + px]
                    guard z.isFinite, z > 0.1 else { continue }
                    let camera = SIMD4<Float>((Float(px) - cx) / fx * z, (cy - Float(py)) / fy * z, -z, 1)
                    let world = entry.frame.transform * camera
                    let band = z < 4 ? 0 : (z < 8 ? 1 : (z < 12 ? 2 : 3))
                    metrics.completeness[band][1] += 1
                    if present(SIMD3(world.x, world.y, world.z), depth: z) { metrics.completeness[band][0] += 1 }
                }
            }
        }
        for entry in kept {
            var hit = 0
            for vertex in entry.vertices {
                let k = key(vertex)
                var found = false
                search: for dx in Int32(-1)...1 { for dy in Int32(-1)...1 { for dz in Int32(-1)...1 where occupied.contains(k &+ SIMD3(dx, dy, dz)) { found = true; break search } } }
                if found { hit += 1 }
            }
            metrics.coverage.append(Float(hit) / Float(max(1, entry.vertices.count)))
        }
        return metrics
    }

    static func gridIntrinsics(_ fixture: Fixture, _ relative: RelativeDepthMap) -> (Float, Float, Float, Float) {
        let sx = Float(relative.width) / Float(fixture.imageResolution.width)
        let sy = Float(relative.height) / Float(fixture.imageResolution.height)
        return (fixture.intrinsics[0][0] * sx, fixture.intrinsics[1][1] * sy,
                fixture.intrinsics[2][0] * sx, fixture.intrinsics[2][1] * sy)
    }

    static func metricDepth(_ relative: RelativeDepthMap,
                            _ calibration: DepthAnythingProcessor.MaximumLikelihoodCalibration,
                            cap: Float) -> [Float] {
        var metric = [Float](repeating: .nan, count: relative.width * relative.height)
        relative.withReadAccess { reader in
            for y in 0..<relative.height {
                for x in 0..<relative.width {
                    if let depth = DepthAnythingProcessor.calibratedMetricDepth(
                        relativeDepth: reader.value(atX: x, y: y), calibration: calibration), depth <= cap {
                        metric[y * relative.width + x] = depth
                    }
                }
            }
        }
        return metric
    }

    @Test("Pan scan reconstruction quality holds its measured baseline")
    func reconstructionQualityBaseline() async throws {
        let metrics = await Self.replay(try Self.loadFixture())
        print("pan scan: \(metrics.summary)")
        #expect(metrics.kept >= 9, "\(metrics.kept) of 11 frames calibrated")

        // Calibration accuracy against each frame's own LiDAR: unbiased near
        // field, and the measured 4-6 m bend must not get worse.
        let nearError = metrics.lidarError.map { Metrics.median($0.map(abs)) }
        #expect(nearError[0] < 0.035 && nearError[1] < 0.04, "near-field |error| \(nearError)")
        #expect(nearError[2] < 0.08, "4-6 m |error| \(nearError[2]) (measured 0.065)")
        #expect(Metrics.median(metrics.lidarError[2]) > -0.08, "4-6 m compression beyond the measured -5.2%")

        // Nothing integrated gets lost on the way into the fused surface.
        #expect((metrics.coverage.min() ?? 0) > 0.99)

        // Scene completeness: everything within LiDAR reach and the first
        // cap step is mapped; 12-18 m is the frame-rate-starved band
        // (measured 37% at the recorded 0.47 Hz).
        let complete = metrics.completeness.map { Float($0[0]) / Float(max(1, $0[1])) }
        #expect(complete[0] > 0.99 && complete[1] > 0.98, "completeness \(complete)")
        #expect(complete[2] > 0.85, "8-12 m completeness \(complete[2]) (measured 0.89)")
        #expect(complete[3] > 0.30, "12-18 m completeness \(complete[3]) (measured 0.37)")

        // Same-surface agreement between consecutive frames.
        let disagreement = metrics.interFrameBands.map { Metrics.median($0) }
        #expect(disagreement[0] < 0.025, "0-4 m disagreement \(disagreement[0]) (measured 0.015)")
        #expect(disagreement[1] < 0.075, "4-8 m disagreement \(disagreement[1]) (measured 0.059)")
        #expect(disagreement[2] < 0.085, "8-12 m disagreement \(disagreement[2]) (measured 0.069)")
    }
}
